### ISSUE TITLE
IE 11 (Insel): filters in navigation panel disappear

### ISSUE THREAD

**Issue by pascalmfrey** [infect-org/frontend#96]
When a filter is chosen either through click action or through the search bar, all filters in the filter navigation panel diappear. Error messages see attached pics below:

![bug_scrollto 13-11-2017 13-25-37](https://user-images.githubusercontent.com/1735457/32725894-3a901844-c877-11e7-8816-9c3aa7d5f14f.png)

![console warnings 13-11-2017 13-27-31](https://user-images.githubusercontent.com/1735457/32725895-3aaadb84-c877-11e7-97d0-e21583aedfc5.png)

![error t component 13-11-2017 13-28-42](https://user-images.githubusercontent.com/1735457/32725896-3ac61872-c877-11e7-94a5-09d72b90f122.png)

**Comment by fxstr** [comment]
@pascalmfrey A very, very good description of the issue, thanks a lot! This issue should have been fixed a few days ago. Could you please let me know what version of the scripts are loaded in your INFECT app?

- right click on the document
- show source
- in the source code, look for a script tag that starts with «main.» and ends with «.js» like `<script async src="/dist/js/main.caeb0c048324fbb634bc.js"></script>``
-  let me know what stands inbetween `main.` and `.js`.

**Comment by pascalmfrey** [comment]
js: main.caeb0c048324fbb634bc.js
css: main.caeb0c048324fbb634bc.css

**Comment by fxstr** [comment]
@pascalmfrey Great, thanks a lot!

**Comment by pascalmfrey** [comment]
Just as an update: tested today again, and noticed the issue still (or again) exists.

**Comment by pascalmfrey** [comment]
As a hint that might help: the call to "scrollTo" is found within the file `mostUsedFilterList.jsx` within the components "filterList" on line 80:

![filterlist](https://user-images.githubusercontent.com/1735457/33511868-5f6b1914-d724-11e7-977a-e18b6f480516.png)

**Comment by fxstr** [comment]
Fixed with https://github.com/infect-org/frontend/commit/90c12febd2d4e65698d48274bc8cd8ed3eaea014
